apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-agent
  labels:
    app: indexer-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer-agent
  template:
    metadata:
      labels:
        app: indexer-agent
    spec:
      containers:
        - name: indexer-agent
          image: indexer-agent:to-be-replaced-by-kustomize
          ports:
            - containerPort: 80
          env:
            - name: INDEXER_AGENT_GRAPH_NODE_ADMIN_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: indexer-agent-graph-node
                  key: admin-endpoint
            - name: INDEXER_AGENT_GRAPH_NODE_STATUS_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: indexer-agent-graph-node
                  key: status-endpoint
